name: CI(Web)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.4

      - name: Install dependencies
        working-directory: ./web
        run: bun install

      - name: Lint
        working-directory: ./web
        run: bun run ci
